Missing node module slow-stream dependency
When I tried your sample by running `node server.js` , my return 

was similar to 

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'slow-stream'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/thomas/node_experiments/leaflet-geojson-stream/example/server.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

A `npm install --save slow-stream` solve the small issue
Commit is to add the missing dep